# Generated by Django 3.2.5 on 2021-08-04 12:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('added_watchlist_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('listing_id', models.ForeignKey(default=16, on_delete=django.db.models.deletion.CASCADE, to='auctions.listing')),
            ],
        ),
    ]
