# Generated by Django 3.2.5 on 2021-08-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210804_1224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='comment_owner',
            new_name='watchlist_owner',
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
