# Generated by Django 4.0.1 on 2022-01-13 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milestone', '0002_event_food_likes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Likes',
            new_name='Like',
        ),
    ]
