# Generated by Django 4.0.1 on 2022-01-21 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestone', '0006_food_ratings_food_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='image_url',
            field=models.CharField(blank=True, default=None, max_length=1024, null=True),
        ),
    ]
